### PR TITLE
Update autoloader.php

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by AXeL-dev** [comment]
Hey,
can i know what kind of issue did you got with the autoloader class?
also, i don't see for wich reason did you remove the inclusions with dol_include_once() function in the DebugBar class & replace them with auto-inclusions in the autoloader class.

**Comment by frederic34** [comment]
the dolistore version did'nt work for me

**Comment by AXeL-dev** [comment]
hum, can you give me more informations about the module version & your dolibarr version, so i can try to reproduce the bug?

**Comment by frederic34** [comment]
Dolibarr 7.0.1 debugBar from dolistore
i restore the original code:
[Sun Sep 16 17:35:00.617316 2018] [:error] [pid 16672] [client xxxxx:52680] PHP Fatal error:  Class 'DolibaseModule' not found in /srv/datadisk01/jails/xxxxxxx-dev/xxxxxx/htdocs/custom/debugbar/core/modules/modDebugBar.class.php on line 11, referer: https://xxxxx-dev.fr/admin/modules.php?mainmenu=home
[Sun Sep 16 17:35:00.617397 2018] [:error] [pid 16672] [client xxxxx:52680] PHP Stack trace:, referer: https://xxxxx-dev.fr/admin/modules.php?mainmenu=home
[Sun Sep 16 17:35:00.617422 2018] [:error] [pid 16672] [client xxxxx:52680] PHP   1. {main}() /srv/datadisk01/jails/xxxxxdev/xxxxxxx/htdocs/admin/modules.php:0, referer: https://xxxxxx-dev.fr/admin/modules.php?mainmenu=home
[Sun Sep 16 17:35:00.617441 2018] [:error] [pid 16672] [client xxxxxx:52680] PHP   2. include_once() /srv/datadisk01/jails/xxxxxx-dev/xxxxxx/htdocs/admin/modules.php:314, referer: https://xxxxxx-dev.fr/admin/modules.php?mainmenu=home

**Comment by AXeL-dev** [comment]
okay, so from the message i see, the error is related to DolibaseModule class @see [dolibase](https://github.com/AXeL-dev/dolibase) & not from the Debugbar class, so what is your PHP version? ( because i do not have a such issue on my PHP 7.0.x)

**Comment by frederic34** [comment]
extracted with 7zip and uploaded with filezilla seems to be the pb...

**Comment by AXeL-dev** [comment]
hum, i see, so does it work now using the dolistore version?

**Comment by frederic34** [comment]
yes, i close

**Pull request closed without merging**
